apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx
  namespace: nginx
spec:
  scaleTargetRef:
    name: nginx
  triggers:
  - type: prometheus
    metadata:
      metricName: http_requests_total
      query: sum(rate(nginx_http_requests_total[1m]))
      serverAddress: http://prometheus-operated.monitoring.svc.cluster.local:9090
      threshold: "5"
  minReplicaCount: 1
  maxReplicaCount: 3
  pollingInterval: 5
